[project]
name = "purch-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "django-bootstrap5>=25.2",
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "gunicorn>=21.2.0",
]

